name: Sync to GitLab

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Sync GitHub -> GitLab
        uses: adambirds/sync-github-to-gitlab-action@v1.3.0
        with:
          gitlab_url: ${{ secrets.GITLAB_URL }}
          gitlab_username: ${{ secrets.GITLAB_USERNAME }}
          gitlab_token: ${{ secrets.GITLAB_TOKEN }}
